server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Redirige toutes les routes vers index.html (nécessaire pour Angular Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le gateway pour les appels API
    location /api/ {
        proxy_pass http://gateway-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
