spring.application.name=order-service
server.port=8082

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/ecommercedb}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=order_schema
spring.jpa.show-sql=true

product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}