spring.application.name=product-service
server.port=8081

# PostgreSQL — les valeurs réelles viendront des variables d'environnement Render
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/productdb}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true